server:
  port: 9003
spring:
  application:
    name: VIDEO-USERS
  cloud:
    nacos:
      server-addr: 192.168.150.3:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.150.3:3306/video?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

# 日志
logging:
  level:
    top.liguapi.admin.mapper: debug